name: Release OTA

on:
  workflow_dispatch:   # 手动触发
  workflow_run:       # 在 Build workflow 完成后触发
    workflows: ["Build releases"]   # 填你 Build workflow 的名字
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync OTA
        run: |
          mkdir -p ota
          wget -q https://github.com/zhiern/ZeroWrt/releases/download/OpenWrt-v24.10.2/x86_64.json -O x86_64.json
          wget -q https://github.com/zhiern/ZeroWrt/releases/download/OpenWrt-v24.10.2/rockchip.json -O rockchip.json
          jq -s '.' x86_64.json rockchip.json > ota/ota.json

      - name: Release OTA
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ftp_address }}
          username: ftpopenwrt
          password: ${{ secrets.ftp_password }}
          server-dir: ota/
          local-dir: ota/
          dangerous-clean-slate: true
